name: openjmu_server_status
description: A Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cookie_jar: 1.0.1
  device_info: ^0.4.1+4
  dio: 3.0.8
  dio_cookie_manager: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true